oc delete secret aggregated-logging-curator-dockercfg-3m777       
oc delete secret aggregated-logging-curator-token-0bjrx           
oc delete secret aggregated-logging-curator-token-ht3zk           
oc delete secret aggregated-logging-elasticsearch-dockercfg-rxttz 
oc delete secret aggregated-logging-elasticsearch-token-g3i73     
oc delete secret aggregated-logging-elasticsearch-token-p73lg     
oc delete secret aggregated-logging-fluentd-dockercfg-eod76       
oc delete secret aggregated-logging-fluentd-token-8tdbc           
oc delete secret aggregated-logging-fluentd-token-v5yly           
oc delete secret aggregated-logging-kibana-dockercfg-lp9q5        
oc delete secret aggregated-logging-kibana-token-9h19o            
oc delete secret aggregated-logging-kibana-token-wet4b            
oc delete secret builder-dockercfg-0ac6x                          
oc delete secret builder-token-0cdcw                              
oc delete secret builder-token-wdvf0                              
oc delete secret default-dockercfg-j27su                          
oc delete secret default-token-ut7rc                              
oc delete secret default-token-y3xdh                              
oc delete secret deployer-dockercfg-kgwsk                         
oc delete secret deployer-token-qk0v4                             
oc delete secret deployer-token-rua41                             
oc delete secret logging-deployer-dockercfg-vxdvb                 
oc delete secret logging-deployer-token-0e1pi                     
oc delete secret logging-deployer-token-9qxko                     
